In [1]:
import numpy as np
t1=(1,2,3)
ar1=np.array(t1)
ar1


array([1, 2, 3])

In [2]:
import numpy as np
t1={1,2,3}
ar1=np.array(t1)
ar1

array({1, 2, 3}, dtype=object)

In [3]:
class c1:
    name = "hari"
    age = 18
obj = c1()
print(obj.name)
print(obj)


hari


In [4]:
t1="hello"
ar1=np.array(t1)
ar1.dtype

dtype('<U5')

In [5]:
t1={"a":100, "b":200}
ar1=np.array(t1)
ar1


array({'a': 100, 'b': 200}, dtype=object)

In [6]:
ar1.tolist()

{'a': 100, 'b': 200}

In [7]:
ar2 = [1,2,3,4,5]
np_ar =np.array(ar2)

In [8]:
ar2

[1, 2, 3, 4, 5]

In [9]:
#to add multiple values:
new_ar = np.append(np_ar, [2,4,6,7])
new_ar

array([1, 2, 3, 4, 5, 2, 4, 6, 7])

In [10]:
#to insert()
#based on the index value to add the elemnt into array:
new_ar = np.insert(np_ar,2,123 )
new_ar

array([  1,   2, 123,   3,   4,   5])

In [11]:
#to insert multiple values in the array
#np.insert(array_to_be_modified,index_position,values in list or tuple)
new_ar = np.insert(np_ar,2,(456,333,37))
new_ar

array([  1,   2, 456, 333,  37,   3,   4,   5])

In [12]:
#1 DELETE FROM AN ARRAY 1
np_ar

array([1, 2, 3, 4, 5])

In [14]:
nr = np.delete(np_ar,np.where(np_ar==3))
nr

array([1, 2, 4, 5])

In [15]:
class c1:
    name = "mohan"
    age = 20
obj = c1()
print(obj.name)
print(obj)


mohan


In [16]:
#to delete number of values in array:
nr = np.setdiff1d(np_ar, [1.0,4,3,2])
nr


array([5])

In [18]:
#to delete based on index position:
nr=np.delete(np_ar,3)
nr

array([1, 2, 3, 5])

In [19]:
#to delete multiple values based on index position:
nr = np.delete(np_ar, [1,2])
nr

array([1, 4, 5])

In [20]:
l1 =[1,2,3,4,5,56,78,98]
new_ar = np.array(l1)
new_ar

array([ 1,  2,  3,  4,  5, 56, 78, 98])

In [21]:
#Filter in numpy
new_ar<30

array([ True,  True,  True,  True,  True, False, False, False])

In [22]:
new_ar[new_ar<30]

array([1, 2, 3, 4, 5])

In [23]:
new_ar

array([ 1,  2,  3,  4,  5, 56, 78, 98])

In [24]:
#print the values < 20 and values >50
#-->for and operation using &
#--> for or operation use
(new_ar<20)&(new_ar>50)

array([False, False, False, False, False, False, False, False])

In [25]:
new_ar[(new_ar>1)&(new_ar<50)]

array([2, 3, 4, 5])

In [26]:
new_ar==3

array([False, False,  True, False, False, False, False, False])

In [27]:
new_ar[new_ar==3]=6

In [28]:
new_ar

array([ 1,  2,  6,  4,  5, 56, 78, 98])

In [29]:
#to create array full of zeroes
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [30]:
#to create 1d array full of zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
#to create 2d array full of zeros
#syntax -->np.zeros([num_of_rows,num_of_cols])
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
#to create array full of ones
np.ones(4)

array([1., 1., 1., 1.])

In [33]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
ar=np.ones([3,7])+1
ar

array([[2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2.]])

In [36]:
#type convert the element in to the array
# to find the numpy data type of element present in array-->dtype
#type(ar)
ar.dtype

dtype('float64')

In [37]:


ar=np.ones([3,7],dtype=int)
ar

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [38]:
ar.dtype

dtype('int32')

In [39]:
#we can convert the values into various bits
#they are
# int8,int16,int32,int64
#float16,float32,float64
#complex64,complex128
#unit32,unit16
ar=np.zeros([2,4],dtype='int16')
ar

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [40]:
ar=np.zeros([2,4],dtype='float16')
ar

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float16)

In [41]:
ar=np.zeros([9,9],dtype='float16')
ar

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float16)

In [42]:
ar=np.zeros([9,9],dtype='int16')
ar

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int16)

In [43]:
ar=np.zeros([2,4],dtype='complex64')
ar

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]], dtype=complex64)

In [44]:
ar=np.zeros([2,4],dtype='uint16')
ar

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint16)

In [45]:
np.int16(ar)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [46]:
np.complex64(ar)

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]], dtype=complex64)

In [47]:
#1.how to craete range of element as array
#2.how to convert a 1d array to multidimensional array
#3.how to create array of identity matrix
#4.how to perform slicing in multidimensional array
#5.how to find mean,median,sum,variance,standard deviation of an array
ar=np.arange(1,37)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [48]:
ar=np.array([1,2,3,4,5,6])
arr2=ar.reshape(2,3)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
ar=np.identity(3)
ar

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
ar = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
sa= ar[0:1, 0:2,1:1]
sa

array([], shape=(1, 2, 0), dtype=int32)

In [51]:
ar = np.arange(25)

In [52]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [53]:
ar1 = ar.reshape(5, 5)
ar1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
ar= np.array([1, 2, 3, 4, 5])
mean = np.mean(ar)
median = np.median(ar)
sum = np.sum(ar)
variance = np.var(ar)
standard_deviation = np.std(ar)
print(mean)
print(median)
print(sum)
print(variance)
print(standard_deviation)

3.0
3.0
15
2.0
1.4142135623730951
